apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vacations
  name: backend
  labels:
    tier: backend
    app: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: backend
          image: vacations-backend:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "768Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  namespace: vacations
  labels:
    tier: backend
  name: backend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30301
  selector:
    tier: backend